## Object detection using SIFT (Not available in openCV 3.0+)

In [ ]:
import cv2
import numpy as np


def sift_detector(new_image, image_template):
    # Function that compares input image to template
    # It then returns the number of SIFT matches between them
    
    image1 = cv2.cvtColor(new_image, cv2.COLOR_BGR2GRAY)
    image2 = image_template
    
    # Create SIFT detector object
    sift = cv2.SIFT()

    # Obtain the keypoints and descriptors using SIFT
    # descriptor는, 이전에 언급했듯, vectors that store information about the key points. match의 대상이 되는 애들임.
    keypoints_1, descriptors_1 = sift.detectAndCompute(image1, None)
    keypoints_2, descriptors_2 = sift.detectAndCompute(image2, None)
    
    ### Flann_Matcher 사용.
    # Define parameters for our Flann Matcher
    FLANN_INDEX_KDTREE = 0 # 초기값 0으로 설정
    index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 3) # tree가 많을수록 complicated, slower
    search_params = dict(checks = 100) # how many matches are going to try to compute

    # Create the Flann Matcher object
    flann = cv2.FlannBasedMatcher(index_params, search_params)

    # Obtain matches using K-Nearest Neighbor Method
    # the result 'matchs' is the number of similar matches found in both images
    # descriptor 1과 2가 가장 가까운 것들. (similar matches found in both img.)
    matches = flann.knnMatch(descriptors_1, descriptors_2, k=2)

    # Store good matches using Lowe's ratio test
    # flannbasedmatcher는 정확도가 높지 않은 대신 속도가 빠르다. 정확성을 높이기 위해 사용하는 게 lowe's ratio test.
    # distance는 numpy func이고, m.distance가 기준을 통과하면 good_match에 append한다.
    good_matches = []
    for m,n in matches:
        if m.distance < 0.7 * n.distance:
            good_matches.append(m) 

    # 결과적으로 중요한 건 'how many matches are in'이기 때문에 len() 결과값을 리턴한다.
    return len(good_matches)

# 1. 웹캠 Stream을 실행한다.
cap = cv2.VideoCapture(0)

# Load our image template, this is our reference image
# 2. template를 불러온다. 
image_template = cv2.imread('images/box_in_scene.png', 0) 

while True:

    # 3. Get webcam images
    ret, frame = cap.read()

    # 4. Get height and width of webcam frame
    height, width = frame.shape[:2]

    # 4.1 Define ROI Box Dimensions. 
    top_left_x = width / 3
    top_left_y = (height / 2) + (height / 4)
    bottom_right_x = (width / 3) * 2
    bottom_right_y = (height / 2) - (height / 4)
    
    # 4.2 Draw rectangular window for our region of interest   
    cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), 255, 3)
    
    # 5. Crop window of observation we defined above. 이 위치를 가져와서 template과 비교할 예정.
    cropped = frame[bottom_right_y:top_left_y , top_left_x:bottom_right_x]
    
    # 6. Flip frame orientation horizontally. 거울모드로 돌려놓은 거라고 보면 된다. 이게 more natural하다고.
    frame = cv2.flip(frame,1)
    
    # 7. Get number of SIFT matches. cropped 이미지와 image template를 받아서 match 작업을 진행함.
    matches = sift_detector(cropped, image_template)

    # 8. Display status string showing the current no. of matches. 얼마나 많은 match / key points가 detected되는지.
    # image와 target image 사이의.
    cv2.putText(frame,str(matches),(450,450), cv2.FONT_HERSHEY_COMPLEX, 2,(0,255,0),1)
    
    # 9. Our threshold to indicate object deteciton
    # We use 10 since the SIFT detector returns little false positves. 
    # 10으로 설정했다는 건, 10개 이상 match가 감지될 시 'object detected'로 인식하는 것.
    # 그게 바로 아래 if문이다.
    threshold = 10
    
    # If matches exceed our threshold then object has been detected
    if matches > threshold:
        cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
        cv2.putText(frame,'Object Found',(50,50), cv2.FONT_HERSHEY_COMPLEX, 2 ,(0,255,0), 2)
    
    cv2.imshow('Object Detector using SIFT', frame)
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()   

#### Flannbased matching is quite fast, but not the most accurate. Other matching methods include:

BruteForce... Flannbased보다는 accurate하다고.

- BruteForce
- BruteForce-SL2 (not in the documentation, BUT this is the one that skeeps the squared root !)
- BruteForce-L1
- BruteForce-Hamming
- BruteForce-Hamming(2)


## ORB 사용하기.

그런데, ORB를 써서 결과를 내보면 위의 SIFT보다는 결과가 좋지 않다. 잘못된 이미지를 detected표시할 수 있음.

& 단순 이미지를 떠나서, 만약 rotation of image같은 걸 detect하고 싶다면 CNN 형태의 solution이 필요할 수 있다. ORB 대신.

https://www.cs.toronto.edu/~guerzhoy/oriviz/crv17.pdf



In [1]:
import cv2
import numpy as np


def ORB_detector(new_image, image_template):
    # Function that compares input image to template
    # It then returns the number of ORB matches between them
    
    image1 = cv2.cvtColor(new_image, cv2.COLOR_BGR2GRAY)

    # Create ORB detector with 1000 keypoints with a scaling pyramid factor of 1.2
    orb = cv2.ORB_create(1000)

    # Detect keypoints of original image
    # None는 image mask를 쓸지 말지 결정하는 파라미터 부분. 안 쓸 거라 None.
    (kp1, des1) = orb.detectAndCompute(image1, None)
#     print(des1)
    # Detect keypoints of template image
    (kp2, des2) = orb.detectAndCompute(image_template, None)
#     print(des2)
    # Create matcher 
    # Note we're no longer using Flannbased matching
    # Norm_hamming은 distance matric이며, crossCheck은 True로 설정.
    bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)

    # Do matching
    matches = bf.match(des1,des2)

    # Sort the matches based on distance.  Least distance
    # is better
    # 정렬할 수 있음을 보여주려고 sorted를 쓴 거고, 실제로는 large distance를 버리면 성능이 올라간다고 함.
    matches = sorted(matches, key=lambda val: val.distance)

    return len(matches)

cap = cv2.VideoCapture(0)

# Load our image template, this is our reference image
image_template = cv2.imread('./MasteringComputerVision-V1.03/Master OpenCV/images/box_in_scene.png', 0) 
# image_template = cv2.imread('images/kitkat.jpg', 0) 

while True:

    # Get webcam images
    ret, frame = cap.read()
    
    # Get height and width of webcam frame
    height, width = frame.shape[:2]

    # Define ROI Box Dimensions (Note some of these things should be outside the loop)
    top_left_x = int(width / 3)
    top_left_y = int((height / 2) + (height / 4))
    bottom_right_x = int((width / 3) * 2)
    bottom_right_y = int((height / 2) - (height / 4))
    
    top = (top_left_x, top_left_y)
    bottom = (bottom_right_x, bottom_right_y)
    # Draw rectangular window for our region of interest
    cv2.rectangle(frame, top, bottom, 255, 3)
    
    # Crop window of observation we defined above
    cropped = frame[bottom_right_y:top_left_y , top_left_x:bottom_right_x]

    # Flip frame orientation horizontally
    frame = cv2.flip(frame,1)
    
    # Get number of ORB matches 
    matches = ORB_detector(cropped, image_template)
    
    # Display status string showing the current no. of matches 
    output_string = "Matches = " + str(matches)
    cv2.putText(frame, output_string, (50,450), cv2.FONT_HERSHEY_COMPLEX, 2, (250,0,150), 2)
    
    # Our threshold to indicate object deteciton
    # For new images or lightening conditions you may need to experiment a bit 
    # Note: The ORB detector to get the top 1000 matches, 350 is essentially a min 35% match
    threshold = 350
    
    # If matches exceed our threshold then object has been detected
    if matches > threshold:
        cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
        cv2.putText(frame,'Object Found',(50,50), cv2.FONT_HERSHEY_COMPLEX, 2 ,(0,255,0), 2)
    
    cv2.imshow('Object Detector using ORB', frame)
    
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()   

[[117 241  25  46  24  77  71 216   2 224 169  12 214 213  65  48 152 221
   92 114  75  35 250  57 249 213   5  60  72  59   2 112]
 [121 249  25 100  80 207  71 252  35 224 168  12 115 215  65  48 156 252
   84 110  73  58 216  61 251 205   5  56 104 178  66  56]
 [136 159 123  89 114 232 185  55 124  13 126 242 185  39 164  49  46  58
  134   8 178 184  36 127  70  47  50 193 119 128 101 233]
 [ 27 221  82 188 211 150  30 119  61  72 248 199  44 190  38 212 238 171
  151 164 109 155  16 239 178 246  10 131  59  68 169  95]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[114  33 130 ...  62  43 142]
 [ 11 183 249 ... 198 131 241]
 [ 60  85 123 ... 251 108 115]
 ...
 [216 144 190 ...   1   5  83]
 [171  77  32 ... 221 248 244]
 [ 27 157  82 ...  86 169 223]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46

[[  9 142 215 ... 192 107 133]
 [234 109 246 ... 244 235 138]
 [  1  46 157 ... 224  67 169]
 ...
 [171  92  36 ... 221 248 246]
 [ 56 139 126 ...   0 236 202]
 [ 26 158  66 ... 196 169 155]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 73   5 217 ... 250   1 169]
 [ 72 128  90 ... 162  33  33]
 [129 174 205 ... 224  83 137]
 ...
 [ 56 139 126 ... 128 236 202]
 [218  43 240 ...  12 135 171]
 [ 26 158  82 ... 196 169 155]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[  1 174 222 ... 200 203 133]
 [129 174 207 ... 224  83 169]
 [ 79 182 247 ... 196 167 247]
 ...
 [220  80 191 ...   3  37 115]
 [ 43  77  36 ... 221 248 246]
 [ 27  93   3 ...  86 169 223]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[118  40 150 ...  63 107 134]
 [143 220 252 ... 252 241 241]
 [  1 175 215 ... 128 193 169]
 ...
 [ 83 207   2 ...  86  57 140]
 [220  80 191 ...   1   5 115]
 [ 27 157  83 ...  86 171 223]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[198  14 199 ... 249  49 133]
 [216 157 182 ... 228 167 123]
 [143 189 242 ... 252 211 241]
 ...
 [222  80 190 ...   1  37  83]
 [ 56 155 126 ...   0 174 202]
 [ 26 159  82 ... 196 169 219]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 63 181 176 ...  79 241 134]
 [143 189 250 ... 236 211 245]
 [143 212 108 ... 252 209 241]
 ...
 [ 56 139 126 ...   4 238 202]
 [ 67 253  35 ...   4 181  92]
 [ 26 159  82 ... 196 169 219]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[254 124 115 ... 255  39 247]
 [167 238 196 ... 125 218 140]
 [139 191 123 ... 172 211 253]
 ...
 [154 207  18 ...  84  47 142]
 [170  93  61 ...  92 212 250]
 [ 26  31 114 ... 196 169 155]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 41 225  97 ... 134 210 252]
 [ 41 241  97 ... 138 194 244]
 [139 181 248 ... 254 223 253]
 ...
 [170  29 189 ...  92 212 234]
 [ 14 217 191 ...  93 245 246]
 [ 26  31  82 ... 196 169 155]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 47 161 193 ... 239 218 132]
 [143 252 110 ... 252 253 245]
 [143 158 255 ... 245 161 249]
 ...
 [220  80  63 ...   3  37 115]
 [ 39 150 107 ... 139 112 117]
 [ 26  29  82 ... 212 169 155]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 96 164 184 ...  66 198  42]
 [250 237 150 ... 124 169  14]
 [139 149 244 ... 246 211 251]
 ...
 [ 46 249 171 ...  93 245 246]
 [ 58 143  26 ...   4 175 206]
 [ 31  82 226 ... 159 120  85]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[  5  31 215 ... 251 225 177]
 [ 47 161 193 ... 135 210 180]
 [ 61 223 105 ... 187 112 241]
 ...
 [204  16 187 ...   1   5 115]
 [ 58 143  26 ...   4 174 206]
 [ 23  18 226 ... 143 120  85]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[195 191 173 ...  76 214  95]
 [ 95 124 242 ... 255 103 247]
 [ 61 223 105 ... 187 112 241]
 ...
 [170 249  57 ...  93 213 251]
 [204  80 191 ...   1 133 115]
 [ 14 217  59 ...  29 181 242]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[216 114 126 ... 149  39 217]
 [216 132  22 ...  76 173   6]
 [ 88 141 150 ... 108 168  10]
 ...
 [  1  67 107 ... 186 240 248]
 [200  80  53 ... 147   5 115]
 [184  52  57 ...  72 214 226]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 33  63 185 ... 250 210 233]
 [ 45 239  41 ... 251  80 240]
 [ 11 187 255 ... 166 143 253]
 ...
 [200  80  53 ... 147   5 115]
 [  6 241 191 ...  23 165 243]
 [168  44  57 ...  72 214 226]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[254 109 148 ... 117 238  10]
 [ 15 252 252 ... 253 221 245]
 [ 37 239  41 ... 186 208 241]
 ...
 [200  80  53 ... 147   5 115]
 [ 23  22  99 ... 207 120 117]
 [184  52  57 ...  72 214 226]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[169 240  17 ... 121  74 167]
 [ 89  22 253 ... 241  70 113]
 [233 123 120 ... 187  82  99]
 ...
 [204  48 187 ...   1  37  83]
 [184 100 121 ...  72  86 226]
 [ 27 221   3 ...   4 169  94]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[230  98 228 ... 223 222  78]
 [ 44  37 113 ... 235  86 224]
 [ 44 165 113 ... 234  86 226]
 ...
 [  3  73  67 ... 190 113 173]
 [249  36 120 ... 216 214 226]
 [ 27 157   2 ...   4 169  94]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 41 109 121 ... 147  70 168]
 [108 253

[[254 249 182 ...  61  47  87]
 [ 15 242 255 ... 255 255 243]
 [131 223 127 ... 244 165 251]
 ...
 [162  16 126 ...   8  61 251]
 [173 108 101 ... 169 114 244]
 [170 186 160 ...  77  92 143]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 92 165 220 ... 251 195   1]
 [130 140   2 ... 120 176 136]
 [164 173   2 ...  90 176 136]
 ...
 [  2 221  58 ...  24 177 223]
 [ 13 209 127 ... 163 161  33]
 [ 73  77 127 ... 242 194  41]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[252  32 220 ... 251 195   1]
 [220 108 212 ... 251  66   0]
 [252  97 212 ... 123  65   0]
 ...
 [ 19  75  66 ... 143  57 221]
 [ 75 219 127 ... 140 117 255]
 [ 75 122 123 ... 134 111 251]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 16 157  31 ... 130 196  59]
 [ 61 109 105 ... 243 102 242]
 [240  92  63 ... 176  70  42]
 ...
 [232 166 158 ... 192 195   9]
 [ 41 225  57 ...   8 214 238]
 [ 18 143  46 ...  10 181  75]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 17 178 255 ... 200 113 241]
 [ 21 182 255 ... 168 241 241]
 [ 87  58 125 ... 137 241 241]
 ...
 [234 189 182 ...  92 239 223]
 [198 172 148 ...  71 143  14]
 [ 76 168 252 ... 200  86 192]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[120 176  60 ...  68 142  83]
 [ 60  58 188 ... 197 142  83]
 [142 253 182 ... 125 189 223]
 ...
 [111 105 194 ...  55 122  94]
 [134 176 186 ...   5 175 214]
 [142 249 179 ...  93 167 246]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[201  20  31 ... 242   3  57]
 [  0 136 155 ... 128 165  51]
 [ 16 157  31 ... 130 228  43]
 ...
 [ 63 233  71 ...  63 114 134]
 [210  85  95 ... 176 165  49]
 [ 75 181  53 ...  68 141  63]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[216  54 152 ... 192   6  75]
 [  0 152 187 ...   0 167 179]
 [ 88 157  31 ... 130 196  43]
 ...
 [191 201  71 ...  63 122 134]
 [ 75 149  55 ...  78 141  63]
 [218  81 119 ... 180 165 123]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 57  29 108 ... 248 208 124]
 [114   0  58 ...   8  35 155]
 [ 80  18  61 ...   8 133  51]
 ...
 [216  80  55 ...  32  37  59]
 [ 51 135 106 ... 142 245  81]
 [218  88 103 ... 181  37 123]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[  8 152 155 ... 128  37  59]
 [ 61 109 105 ... 251  70 234]
 [ 45 133 125 ... 163  66 242]
 ...
 [ 42 248 112 ... 140  85 219]
 [207 190 253 ... 240 133 113]
 [203  16 252 ... 204  97 113]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[  0 144 191 ... 128 167 251]
 [ 61 141 121 ... 163  74 242]
 [ 16 157  31 ... 130 228 107]
 ...
 [ 78  22 178 ... 229 181 115]
 [201  92  61 ... 209 161 115]
 [ 79  22 247 ... 231  37 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 64 188  27 ... 192 133  56]
 [252 120 251 ... 241  70  42]
 [205  48 181 ... 113 195  50]
 ...
 [ 19  27  59 ... 162 103 121]
 [122 120  58 ...  12 110 126]
 [239 104 163 ...  37 114 228]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[244 110 158 ... 113 139   3]
 [ 72 177 221 ... 128 199  41]
 [100 125 111 ... 187  86 112]
 ...
 [216 112 121 ... 163   6 115]
 [106  48  56 ...  13  94 246]
 [192 204  44 ...  88 149 122]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[212 108 158 ... 113  66   3]
 [213 119 157 ... 113   3  33]
 [ 61 253  23 ... 163  98 240]
 ...
 [ 25  77  19 ... 179  33  41]
 [234  48 120 ...  13  94 246]
 [ 13 110 209 ... 243 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[205  84 157 ... 249  64  32]
 [ 61 253  21 ... 179 194 240]
 [181  79 221 ... 251  16  33]
 ...
 [138 248 186 ...   4 175 255]
 [106  48 120 ...  12  94 238]
 [ 13 239 209 ... 243 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[210 238 158 ... 112 135  75]
 [228 239 156 ... 121 203   2]
 [ 53 189  23 ...  50 163 240]
 ...
 [ 10 180 226 ...   6 189 222]
 [ 10 190 186 ...  76 189 223]
 [202 176 190 ...  12 157 222]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[208 188 189 ...  96 135 123]
 [228 239 156 ... 121 203   2]
 [ 21 253  23 ...  50 163 176]
 ...
 [ 61  20 113 ... 243  70 113]
 [  2 164  98 ...  70 189 222]
 [173 227 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[208 174 156 ... 112 134  91]
 [244 175 156 ... 113 139   2]
 [ 20 253  23 ... 114 163 177]
 ...
 [ 10 181  98 ...  78 173 222]
 [ 10 188  58 ...  12 189 223]
 [173 235 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[112 232  19 ...  51  98  42]
 [173 182  93 ... 241 194  33]
 [ 13 183  73 ... 162 163 177]
 ...
 [  2 167  98 ...   6 189 206]
 [208 112 123 ... 163   5 115]
 [141 221 249 ... 247 225 245]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[244 174 156 ... 112 134  11]
 [200 157 255 ... 196 143 107]
 [117 229  68 ... 178 162   0]
 ...
 [ 61  86 119 ... 179  96 241]
 [  2 167  98 ...   6 173 206]
 [208  84 123 ... 163  39 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[229 239 156 ... 115 139 130]
 [ 20 253  31 ...  19  35 185]
 [ 13 247  89 ... 242 163 177]
 ...
 [133  95 103 ... 187 113 181]
 [  2 167  98 ...   6 189 206]
 [208  84 123 ... 163  39 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[244 174 140 ... 112 134  75]
 [116  64 151 ...  51  34  32]
 [237 108 181 ... 113  75 164]
 ...
 [ 33  23 115 ... 138 116 245]
 [  2 167  98 ...   6 189 206]
 [157  95 249 ... 247 196 241]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[212 184 188 ...  96 135 122]
 [ 31 113 115 ... 178 163 240]
 [173  36 149 ... 125  75 164]
 ...
 [ 14 179 186 ...  71  46 211]
 [208  80 123 ... 163  37 115]
 [157  95 249 ... 247 196 113]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[196 126 140 ... 113 139  67]
 [133 228 157 ... 113  11 132]
 [204  45 189 ... 241 198  40]
 ...
 [ 14 177 186 ...  70 175 211]
 [208  80 123 ... 162  37 113]
 [159  95 249 ... 247 196 113]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[229 239 156 ... 113 139   8]
 [116  68  23 ...  51  38  34]
 [237 104 149 ... 117  74 132]
 ...
 [112  58 190 ...  80   7  91]
 [157  95 249 ... 247 236 245]
 [141 239 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[116 108  17 ...  51  34  40]
 [149 106 157 ... 241  66  36]
 [ 28 253  95 ...  50  39 184]
 ...
 [ 43 184 242 ...  14  91 159]
 [147  94  99 ... 191 113 253]
 [189  85 105 ... 251  82 241]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[213  40 157 ... 241   3   0]
 [229 239 156 ... 112 139   2]
 [245 229 204 ... 242 194   0]
 ...
 [ 33  19 127 ... 138 116 249]
 [138 184 178 ...   5 173 223]
 [229 227 221 ... 240 195 161]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[212 180 189 ... 112 135  42]
 [229 111 156 ... 113 139 128]
 [ 44 180 177 ...  66 199 163]
 ...
 [189  85 105 ... 251  82 241]
 [ 46 178 186 ... 199 166 243]
 [129 220  63 ... 248 161 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[228 239 156 ... 121 139 130]
 [116  68  21 ...  51  98  34]
 [  5 108 203 ... 250 251 136]
 ...
 [  2 167  98 ...   6 189 206]
 [149  81 123 ... 170  36 115]
 [ 42 178 122 ... 199  38 243]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[228 239 140 ... 113 203  10]
 [ 85  32 140 ... 240   2   0]
 [ 13 151 123 ... 242 171 177]
 ...
 [  2 167  98 ...   6 189 206]
 [159  95 233 ... 247 196 113]
 [173 227 209 ... 248 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[244 239 156 ... 113 203  10]
 [116  64  83 ... 179 102  34]
 [252  57 253 ... 243  70  50]
 ...
 [ 78 177 186 ...  70 175 211]
 [208  80 123 ... 163  37 113]
 [141  95 249 ... 247 196 113]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[100 164 144 ...  67 202   2]
 [236 232 253 ... 243  70  42]
 [ 29 151 114 ... 226 163 145]
 ...
 [138 152 187 ...   4 189 223]
 [145 205  31 ... 248 225 168]
 [159  95 241 ... 247 196 113]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[116  97  95 ... 163 102  34]
 [133 230 157 ... 113 195   4]
 [133 224 157 ... 121 139 128]
 ...
 [ 10 167  98 ...   6 173 206]
 [138 152 178 ...   4 189 223]
 [157  95 249 ... 245 228 113]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[229 111 156 ... 113  11   8]
 [ 81  32 142 ... 226  67   0]
 [143 243  98 ... 134 171 213]
 ...
 [  5  86 127 ... 179  96 177]
 [ 33  23 122 ... 170 100 249]
 [ 10 180  98 ...  14 173 222]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[212  98 159 ... 160  35  32]
 [244 172 156 ... 112 134  90]
 [228 239 156 ... 113 139 130]
 ...
 [189  85 105 ... 251  80 241]
 [186 207  98 ... 140 252  95]
 [159  95 249 ... 247 196 113]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[116  97 223 ... 179  38  32]
 [133 238 157 ... 113   3 164]
 [236  57 249 ... 251  70  34]
 ...
 [ 10 165  98 ...  14 173 222]
 [186 207  98 ... 140 252 223]
 [200 204 188 ...  88 157  75]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[208 176 181 ... 112 135 106]
 [244 239 156 ... 112 198  10]
 [ 25 253  23 ...  18  35 184]
 ...
 [ 27  95 123 ... 151 101 123]
 [ 58 206 106 ... 140 252 219]
 [234  48  56 ...  13  86 246]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[213  32 157 ...  97   3  32]
 [229 108 156 ... 121 203   2]
 [ 20 253  31 ...  50  35 176]
 ...
 [253  80 121 ... 159  86 115]
 [138 248 178 ...   5 173 223]
 [186 206 106 ... 140 252 219]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[  9 183  67 ... 242 163 177]
 [ 10  14   5 ...  85 173  85]
 [244 237  13 ... 179  98  32]
 ...
 [ 61  84 113 ... 179 102 241]
 [ 58 206 110 ... 140 252 219]
 [135  22 239 ... 245 185 253]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[236  61 241 ... 235  70  50]
 [238 244 244 ... 140 239 215]
 [  9 183 123 ... 242 163 177]
 ...
 [186 207  98 ... 158 252 223]
 [191  85 115 ... 215 238 247]
 [208  18  63 ...   1   5 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[236  45 253 ... 243  66  40]
 [141 253  29 ...  19 131 240]
 [188 190  88 ... 121  78   3]
 ...
 [191  85 115 ... 215 238 247]
 [ 46 160 184 ...  15 175 198]
 [ 58 206  98 ... 140 124 143]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 28 216  21 ...  51   7 121]
 [ 31 117

[[ 96 224 185 ...  82 198  42]
 [193 157  22 ... 112 163 168]
 [ 65 142 223 ... 248 193  41]
 ...
 [183  30 107 ... 171 112 241]
 [ 14 160 186 ...  15 173 198]
 [ 58 206  98 ... 140 124 207]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[197 189 158 ... 112 171  11]
 [190 233 168 ... 127 252 198]
 [234 237 150 ... 116 238  14]
 ...
 [ 14 176 186 ...  15 175 198]
 [208  16  59 ... 131  37 115]
 [141 251 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 74 254 242 ...  78 239 223]
 [209   6 154 ... 163  66   0]
 [ 19 189 115 ... 135  35 175]
 ...
 [ 14 176 186 ...  15 175 198]
 [208  82  59 ... 131  37 115]
 [141 251 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 29  53 235 ... 242 226 240]
 [241  66 135 ...  35 194  36]
 [201 157 150 ...  80 171  10]
 ...
 [ 58 206  98 ... 140 124 207]
 [138 148  51 ...  14 181 255]
 [141 251 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[236  45 245 ... 251  70  34]
 [ 17  70 151 ...  75  64  32]
 [ 96 228 181 ...  82 198 106]
 ...
 [186 206  98 ... 140 124 207]
 [138 148  59 ...  13  53 223]
 [141 251 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[236  45 245 ... 243  70  32]
 [ 96 228 177 ...  82 198 170]
 [145 135  29 ... 194 161 169]
 ...
 [ 58 206  98 ... 140 124 207]
 [138 148  51 ...  15 181 223]
 [141 251 209 ... 240 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 32 165 177 ...  66 198 234]
 [193 157 158 ...  64 163  10]
 [ 45 229 169 ... 251 210 160]
 ...
 [191  85 114 ... 215 238 247]
 [142 160 184 ...  13 175 198]
 [ 88  80 123 ... 147  37 123]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[108  37 245 ... 251  70  32]
 [143 243 119 ... 148 175  85]
 [ 40 228 177 ...  82 198 170]
 ...
 [191  85 115 ... 215 238 247]
 [216  16  63 ... 129   5 115]
 [173  84 109 ... 184  82 241]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[158 242 115 ...  22 175 117]
 [240   4  13 ... 137 196   0]
 [ 90  59 122 ... 167  39 155]
 ...
 [171 114  98 ...  12  90 199]
 [191  85 114 ... 215 238 247]
 [216  16  63 ... 131   5 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[236  41 245 ... 235  70  34]
 [201 157  22 ... 112  35 138]
 [ 94 249 251 ... 178  39  59]
 ...
 [142 176 186 ...  13 175 198]
 [208  18  63 ... 131  37 115]
 [141 251 209 ... 248 195 169]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 29 117  99 ... 242 226 241]
 [201 157  22 ... 112 163 168]
 [ 62 114 114 ... 191 102 247]
 ...
 [191  85 115 ... 215 238 247]
 [142 160 184 ...  13 175 198]
 [208  18  63 ... 131  37 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 74 182 244 ... 140 231 255]
 [ 92  80 145 ... 122  68  49]
 [ 90 253 178 ... 254 127 219]
 ...
 [191  85 115 ... 215 238 247]
 [174 160 184 ...  13 175 198]
 [208  18  63 ... 129   5 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 96 244 177 ...  82 198  34]
 [193 157  23 ...  64 163  10]
 [129 142 215 ... 224 161  33]
 ...
 [ 62  89 115 ... 151 239 247]
 [142 176 186 ...  13 175 198]
 [216  48  61 ...   1   5 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[124 108 253 ... 243  70  42]
 [  9 119 107 ... 242 163 177]
 [193 149 150 ...  64 163  11]
 ...
 [142 176 186 ...  13 175 198]
 [216  16  59 ... 131  37 115]
 [192 156 188 ...  88 149  75]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[  9 247 107 ... 242 163 177]
 [142 243  99 ...   6 175 213]
 [193 157  22 ...  64  35  11]
 ...
 [ 62  81 115 ... 215 239 247]
 [142 176 186 ...  13 175 198]
 [216  16  59 ... 131  37 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32

[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 79 251 121 ... 151  11 125]
 [ 86 142  44 ...  69 181  67]
 [143 159 127 ... 206 165 125]
 ...
 [ 14 176 186 ...   7 175 214]
 [ 58 206 110 ... 140 124 223]
 [ 10 148  51 ...  14 181 254]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 74 221 182 ...  92 165  94]
 [ 28  93 122 ... 250 102 219]
 [228 164  21 ...  11 194 130]
 ...
 [210  18 190 ...   1   5 115]
 [ 58 202 110 ... 140 252 202]
 [ 10 148  51 ...  14 181 223]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[162 168  49 ...  76 207 206]
 [193 221

[[124  99 104 ... 187  86   2]
 [116 227   0 ...  11  86 130]
 [100 237 153 ...  91 198  42]
 ...
 [208  90  59 ... 131  37 115]
 [136 159 122 ... 128  36 251]
 [220  16 190 ...   1  37  83]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 92 170 152 ... 192 143  19]
 [248 191  28 ...  72 206  11]
 [ 70 142 174 ... 212 169  65]
 ...
 [128 158 123 ... 136 101 233]
 [ 55  87 106 ... 219 244 243]
 [174 253 185 ...  93 215 251]]
[[ 56  73 120 ... 171 118 163]
 [162  32 102 ... 132  66 211]
 [202  16 235 ...  46 117 251]
 ...
 [124 233 172 ... 115 198  98]
 [156   4  30 ... 241 165  34]
 [ 52 165 121 ... 203  86 226]]
[[ 44 181 177 ... 203 198 173]
 [ 77 181 145 ... 113 135  33]
 [253  80 255 ... 243  70 121]
 ...
 [ 63 127 122 ... 215 238 247]
 [ 51 119 122 ... 155 245 211]
 [220  80  62 ...  19  37 115]]
[[ 56  73 120 ... 171 118 163]
 [162  32